### PR TITLE
Add codecov for coverage

### PR DESCRIPTION
**Pull request by williamjamir**

### CODE REVIEW

**Review by FrankKair — COMMENTED** [review]
Awesome contribution, @williamjamir! 👏🏼😁
This is very nice.

**Review by FrankKair — APPROVED** [review]
✅

**Review by FrankKair — APPROVED** [review]
✅

**Review by FrankKair — CHANGES_REQUESTED** [review]
@williamjamir I think there's a conflict with the master branch. Can you try rebasing?

Btw, now I've added you as a collaborator, so you don't need to fork the repo anymore.

**Comment by williamjamir** [comment]
I don't know the reason for this conflict, but since my changes are already on master I will close this PR ;)

**Pull request closed without merging**
